---
title: "Untitled"
date: last-modified
date-format: "dddd, DD/MM/YYYY"
format: 
  html:
    theme: flatly
    code-fold: true
    code-copy: hover
    code-overflow: wrap
    code-tools: true
    df-print: paged
    default-image-extension: svg
    embed-resources: true
    page-layout: full
    reference-location: margin
    title-block-banner: true
    title-block-style: default
    fontsize: .9em
    monofont: 'Fira Code'
execute: 
  warning: false
number-sections: true
toc: true
fig-dpi: 320
dpi: 320
---


# Setup

```{r}
#| label: setup

pacman::p_load(tidyverse, bibliometrix, janitor, stringi, 
               gtsummary, kableExtra)

```

# Import Database and Export 

```{r}
bibds_wost <- convert2df("240418_php.bib", dbsource = "wos", 
                        format = "bibtex") %>% 
  mutate(id = row_number(), 
         .before = 1) %>% 
  rowwise() %>%
  mutate(idR = stri_rand_strings(1, 4), 
         .after = id) %>% 
  ungroup()

#write_csv(bibds_wost, "bibds_wost.csv")
```

# Open Refine

- import dataset (project name: 2024_BiblioIKU_03)
- split AU 
- cluster and edit AU
- Join AU
- split DE
- cluster and edit DE
- join DE
- split SC
- cluster and edit SC
- join SC
- export to bibds_wos_postor.csv

# Import OpenRefine

```{r}
bibds_wos_port <- read_csv("bibds_wos_postor.csv")

bibds_wos_port
```



# Bibliometrix

```{r}
biblioAnalysis(bibds_wos_port) %>% 
  summary(k = 20)
```

```{r}
metaTagExtraction(bibds_wost, Field = "AU_CO", sep = ";")
```



```{r}
fieldByYear(bibds_wost, field = "DE", graph = T)
```



```{r}
biblioNetwork(bibds_wost, analysis = "co-occurrences", 
                             network = "keywords", sep = ";") 
```

