---
title: "2025 - Bibliometric Childhood Obesity"
date: last-modified
date-format: "dddd, DD/MM/YYYY"
format: 
  html:
    theme: flatly
    code-fold: true
    code-copy: hover
    code-overflow: wrap
    code-tools: true
    df-print: paged
    default-image-extension: svg
    embed-resources: true
    page-layout: full
    reference-location: margin
    title-block-banner: true
    title-block-style: default
    fontsize: .9em
    monofont: 'Fira Code'
execute: 
  warning: false
number-sections: true
toc: true
fig-dpi: 320
dpi: 320
---

# Setup

```{r}
#| label: setup

pacman::p_load(tidyverse, googledrive, bibliometrix, janitor, stringi, 
               summarytools)
```

# Import Database and Export

## Search Criteria

- Database: Scopus
- Date Access: 23/02/2025
- Search Term: 

TITLE ( "pediatric" OR "paediatric" OR "childhood" OR "adolescent" OR "youth" ) AND TITLE ( "obesity" OR "obese" OR "overweight" ) AND PUBYEAR > 2003 AND PUBYEAR < 2024 AND ( LIMIT-TO ( DOCTYPE , "ar" ) ) AND ( LIMIT-TO ( PUBSTAGE , "final" ) ) AND ( LIMIT-TO ( SRCTYPE , "j" ) ) AND ( LIMIT-TO ( LANGUAGE , "English" ) )


## Import Database

```{r}
# eval: false

# file is large, save in onedrive

# drive_auth()

temp_file <- tempfile(fileext = ".csv")

drive_download(as_id("1QmaaiDEPm2242yv3yK8n1NrmMtoBlDEA"), 
               path = temp_file, overwrite = TRUE)

pedob_bibds <- convert2df(temp_file, 
                          dbsource = "scopus", 
                          format = "csv", 
                          remove.duplicates = TRUE)

head(pedob_bibds)

write_rds(pedob_bibds, "pedob_bibds.rds")
```


```{r}
pedob_bibds <- read_rds("pedob_bibds.rds")
```

```{r}
dupti <- pedob_bibds %>% 
  count(TI, sort = T) %>% 
  filter(n > 1) %>% 
  pull(TI)

pedob_bibds %>% 
  arrange(TI, PY) %>% 
  filter(TI %in% dupti) %>% 
  mutate(ti_short = str_sub(TI, 1, 100), .before = 1)

```


